### PR TITLE
switch to a dummy package

### PR DESCRIPTION
**Pull request by akhmerov**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by akhmerov** [comment]
@conda-forge-admin please rerender

**Comment by akhmerov** [comment]
@beckermr to follow up on the gitter discussion I'd like to use your kind offer of help:

- Is it possible to avoid packaging the license in a metapackage (or how to do it properly)?
- Can you take a quick look at the recipe: am I on the right track?

**Comment by beckermr** [comment]
Recipe looks good. Our linter will complain if you remove the license. I'd make a copy of it and put it in the repo within the recipe dir. this will keep things happy.

**Comment by beckermr** [comment]
If you do want to archive this feedstock, then this shim package needs to be put into the other package. Otherwise you'll need to keep the source section around so our bots make a shim for each version.

**Pull request closed without merging**
