### PR TITLE
jupyter_sphinx v0.2.0

### PR DESCRIPTION
**Pull request by akhmerov**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by akhmerov** [comment]
@conda-forge-admin, please rerender

**Comment by akhmerov** [comment]
@conda-forge-admin, please rerender

**Comment by akhmerov** [comment]
@SylvainCorlay I think this is good to go.

**Comment by SylvainCorlay** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
